# Generated by Django 2.2.28 on 2025-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songeek_project', '0007_auto_20250312_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers'),
        ),
    ]
