# Generated by Django 2.2.28 on 2025-03-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songeek_project', '0009_auto_20250320_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default.jpeg', upload_to='album_covers'),
        ),
    ]
