# Generated by Django 2.2.28 on 2025-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songeek_project', '0012_auto_20250326_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/profile_photo.jpg', upload_to='profile_images'),
        ),
    ]
