# Generated by Django 2.2.28 on 2025-03-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songeek_project', '0013_auto_20250327_1031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
