# Generated by Django 2.2.28 on 2025-03-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songeek_project', '0013_auto_20250326_2257'),
        ('songeek_project', '0014_auto_20250327_1053'),
    ]

    operations = [
    ]
